spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.sql.init.mode=never
spring.jpa.defer-datasource-initialization=false
logging.level.org.hibernate.SQL=OFF
logging.level.org.hibernate.type.descriptor.sql=OFF
app.cors.allowed-origins=https://front-ciblorgasport.onrender.com,https://*.onrender.com,http://localhost:4200
