spring.application.name=cibl-orga-sport
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:create}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:true}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/glop}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:admin}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:password}
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=false
logging.level.org.hibernate.SQL=OFF
logging.level.org.hibernate.type.descriptor.sql=OFF

server.port=${PORT:8080}

management.endpoints.web.exposure.include=*
management.endpoint.prometheus.enabled=true
management.metrics.export.prometheus.enabled=true

server.address=0.0.0.0

springfox.documentation.swagger-ui.path=/swagger-ui.html

token.signing.key=${TOKEN_SIGNING_KEY:testdutoken123azertyuiiopqsdfghjklmwxcvbn0987654321}

spring.sql.init.mode=${SPRING_SQL_INIT_MODE:always}
spring.jpa.defer-datasource-initialization=true
app.cors.allowed-origins=${APP_CORS_ALLOWED_ORIGINS:http://localhost:4200}
